--------------------------------------------------------
--  Fichier créé - mardi-janvier-05-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEPENSES
--------------------------------------------------------

  CREATE TABLE "WEEDINGMANIA"."DEPENSES" 
   (	"ID" NUMBER, 
	"NUM_TRANSACTION" NUMBER, 
	"DESIGNIATION" VARCHAR2(20 BYTE), 
	"MONTANT" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONNEL
--------------------------------------------------------

  CREATE TABLE "WEEDINGMANIA"."PERSONNEL" 
   (	"IDENTIFIANT" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"NBRJ" VARCHAR2(20 BYTE), 
	"IDR" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INVITE
--------------------------------------------------------

  CREATE TABLE "WEEDINGMANIA"."INVITE" 
   (	"ID" NUMBER, 
	"NOM_FAM" VARCHAR2(20 BYTE), 
	"NBR_PERS" NUMBER, 
	"NBR_AD" NUMBER, 
	"NBR_ENF" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOGIN
--------------------------------------------------------

  CREATE TABLE "WEEDINGMANIA"."LOGIN" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "WEEDINGMANIA"."CLIENT" 
   (	"ID" NUMBER, 
	"IDC" NUMBER, 
	"DAATE" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"TFETE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "WEEDINGMANIA"."RESERVATION" 
   (	"IDENTIFIANT" NUMBER, 
	"SFETE" VARCHAR2(20 BYTE), 
	"NBANDE" VARCHAR2(20 BYTE), 
	"NPH" VARCHAR2(20 BYTE), 
	"NSER" VARCHAR2(20 BYTE), 
	"NTR" VARCHAR2(20 BYTE), 
	"NSEC" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REVENUS
--------------------------------------------------------

  CREATE TABLE "WEEDINGMANIA"."REVENUS" 
   (	"ID_CLIENT" NUMBER, 
	"NOM_CLIENT" VARCHAR2(20 BYTE), 
	"NUMERO_TRANSATION" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"MONTANT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE "WEEDINGMANIA"."ROLE" 
   (	"IDROLE" NUMBER, 
	"NOMROLE" VARCHAR2(20 BYTE), 
	"SALAIRE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SALLE
--------------------------------------------------------

  CREATE TABLE "WEEDINGMANIA"."SALLE" 
   (	"ID_SALLE" NUMBER, 
	"NBR_TAB_RD" NUMBER, 
	"NBR_TAB_RECT" NUMBER, 
	"NBR_TAB_OV" NUMBER, 
	"NBR_CHS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into WEEDINGMANIA.DEPENSES
SET DEFINE OFF;
Insert into WEEDINGMANIA.DEPENSES (ID,NUM_TRANSACTION,DESIGNIATION,MONTANT,TYPE) values ('452','5424','ghhj','45245','fghgh');
Insert into WEEDINGMANIA.DEPENSES (ID,NUM_TRANSACTION,DESIGNIATION,MONTANT,TYPE) values ('0','54245','jhgjg','5','hgjh');
REM INSERTING into WEEDINGMANIA.PERSONNEL
SET DEFINE OFF;
REM INSERTING into WEEDINGMANIA.INVITE
SET DEFINE OFF;
REM INSERTING into WEEDINGMANIA.LOGIN
SET DEFINE OFF;
Insert into WEEDINGMANIA.LOGIN (USERNAME,PASSWORD,NOM,PRENOM,MAIL) values ('za','za','za','za','za');
Insert into WEEDINGMANIA.LOGIN (USERNAME,PASSWORD,NOM,PRENOM,MAIL) values ('h','h','h','h','h');
Insert into WEEDINGMANIA.LOGIN (USERNAME,PASSWORD,NOM,PRENOM,MAIL) values ('d','d','dfg','d','d');
REM INSERTING into WEEDINGMANIA.CLIENT
SET DEFINE OFF;
Insert into WEEDINGMANIA.CLIENT (ID,IDC,DAATE,NOM,PRENOM,TFETE) values ('88','88','??;4',',;p','kk','birthday');
Insert into WEEDINGMANIA.CLIENT (ID,IDC,DAATE,NOM,PRENOM,TFETE) values ('10','2','2','12','1','others');
Insert into WEEDINGMANIA.CLIENT (ID,IDC,DAATE,NOM,PRENOM,TFETE) values ('123','2','12janvier2021','h','h','others');
Insert into WEEDINGMANIA.CLIENT (ID,IDC,DAATE,NOM,PRENOM,TFETE) values ('45','452','452','452','4552','others');
REM INSERTING into WEEDINGMANIA.RESERVATION
SET DEFINE OFF;
Insert into WEEDINGMANIA.RESERVATION (IDENTIFIANT,SFETE,NBANDE,NPH,NSER,NTR,NSEC) values ('1','1','1','1','1','3','3');
Insert into WEEDINGMANIA.RESERVATION (IDENTIFIANT,SFETE,NBANDE,NPH,NSER,NTR,NSEC) values ('0','0','0','0','0','0','0');
Insert into WEEDINGMANIA.RESERVATION (IDENTIFIANT,SFETE,NBANDE,NPH,NSER,NTR,NSEC) values ('2','2','2','2','2','2','2');
REM INSERTING into WEEDINGMANIA.REVENUS
SET DEFINE OFF;
REM INSERTING into WEEDINGMANIA.ROLE
SET DEFINE OFF;
REM INSERTING into WEEDINGMANIA.SALLE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PERSONNEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEEDINGMANIA"."PERSONNEL_PK" ON "WEEDINGMANIA"."PERSONNEL" ("IDENTIFIANT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index INVITE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEEDINGMANIA"."INVITE_PK" ON "WEEDINGMANIA"."INVITE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LOGIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEEDINGMANIA"."LOGIN_PK" ON "WEEDINGMANIA"."LOGIN" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEEDINGMANIA"."CLIENT_PK" ON "WEEDINGMANIA"."CLIENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESERVATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEEDINGMANIA"."RESERVATION_PK" ON "WEEDINGMANIA"."RESERVATION" ("IDENTIFIANT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REVENUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEEDINGMANIA"."REVENUS_PK" ON "WEEDINGMANIA"."REVENUS" ("ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEEDINGMANIA"."ROLE_PK" ON "WEEDINGMANIA"."ROLE" ("IDROLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DEPENSES
--------------------------------------------------------

  ALTER TABLE "WEEDINGMANIA"."DEPENSES" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."DEPENSES" MODIFY ("MONTANT" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."DEPENSES" MODIFY ("DESIGNIATION" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."DEPENSES" MODIFY ("NUM_TRANSACTION" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."DEPENSES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONNEL
--------------------------------------------------------

  ALTER TABLE "WEEDINGMANIA"."PERSONNEL" ADD CONSTRAINT "PERSONNEL_PK" PRIMARY KEY ("IDENTIFIANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEEDINGMANIA"."PERSONNEL" MODIFY ("IDR" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."PERSONNEL" MODIFY ("NBRJ" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."PERSONNEL" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."PERSONNEL" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."PERSONNEL" MODIFY ("IDENTIFIANT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVITE
--------------------------------------------------------

  ALTER TABLE "WEEDINGMANIA"."INVITE" ADD CONSTRAINT "INVITE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEEDINGMANIA"."INVITE" MODIFY ("NBR_ENF" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."INVITE" MODIFY ("NBR_AD" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."INVITE" MODIFY ("NBR_PERS" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."INVITE" MODIFY ("NOM_FAM" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."INVITE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "WEEDINGMANIA"."LOGIN" ADD CONSTRAINT "LOGIN_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEEDINGMANIA"."LOGIN" MODIFY ("MAIL" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."LOGIN" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."LOGIN" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."LOGIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."LOGIN" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "WEEDINGMANIA"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEEDINGMANIA"."CLIENT" MODIFY ("TFETE" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."CLIENT" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."CLIENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."CLIENT" MODIFY ("DAATE" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."CLIENT" MODIFY ("IDC" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."CLIENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "WEEDINGMANIA"."RESERVATION" ADD CONSTRAINT "RESERVATION_PK" PRIMARY KEY ("IDENTIFIANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEEDINGMANIA"."RESERVATION" MODIFY ("NSEC" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."RESERVATION" MODIFY ("NTR" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."RESERVATION" MODIFY ("NSER" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."RESERVATION" MODIFY ("NPH" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."RESERVATION" MODIFY ("NBANDE" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."RESERVATION" MODIFY ("SFETE" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."RESERVATION" MODIFY ("IDENTIFIANT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REVENUS
--------------------------------------------------------

  ALTER TABLE "WEEDINGMANIA"."REVENUS" ADD CONSTRAINT "REVENUS_PK" PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEEDINGMANIA"."REVENUS" MODIFY ("MONTANT" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."REVENUS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."REVENUS" MODIFY ("NUMERO_TRANSATION" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."REVENUS" MODIFY ("NOM_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."REVENUS" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLE
--------------------------------------------------------

  ALTER TABLE "WEEDINGMANIA"."ROLE" ADD CONSTRAINT "ROLE_PK" PRIMARY KEY ("IDROLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEEDINGMANIA"."ROLE" MODIFY ("SALAIRE" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."ROLE" MODIFY ("NOMROLE" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."ROLE" MODIFY ("IDROLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SALLE
--------------------------------------------------------

  ALTER TABLE "WEEDINGMANIA"."SALLE" MODIFY ("NBR_CHS" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."SALLE" MODIFY ("NBR_TAB_OV" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."SALLE" MODIFY ("NBR_TAB_RECT" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."SALLE" MODIFY ("NBR_TAB_RD" NOT NULL ENABLE);
  ALTER TABLE "WEEDINGMANIA"."SALLE" MODIFY ("ID_SALLE" NOT NULL ENABLE);
